### ISSUE TITLE
Which license is this repository using?

### ISSUE THREAD

**Issue by lupohan44** [azhuge233/SteamDB-FreeGames#2]
I want to create a new project base on this one, use steamdb and ASF.

**Comment by azhuge233** [comment]
<a href="https://github.com/azhuge233/SteamDB-FreeGames/blob/master/LICENSE" target="_blank">License</a> created.

**Comment by lupohan44** [comment]
Thanks for that.
I have created a new repository https://github.com/lupohan44/SteamDBFreeGamesClaimer
